import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft } from 'lucide-react-native';
import { Alert, StyleSheet } from 'react-native';
import { ErrorState, LoadingState } from '@/components/feedback';
import { AppHeader, IconButton, Screen } from '@/components/ui';
import { HabitForm, habitColorOptions, useHabitDetails, useUpdateHabitMutation, type HabitColorToken, type HabitFormValues, type HabitIconName } from '@/features/habits';
import { useAuth } from '@/hooks/use-auth';
import { spacing } from '@/theme';
export default function EditHabitScreen() { const { user } = useAuth(); const { id } = useLocalSearchParams<{ id?: string }>(); const habitId = typeof id === 'string' ? id : undefined; const userId = user?.id ?? ''; const details = useHabitDetails(userId, habitId); const mutation = useUpdateHabitMutation(userId, habitId ?? 'missing'); const habit = details.habit; const colorToken = habitColorOptions.find((item) => item.color.toLowerCase() === habit?.color.toLowerCase())?.token ?? 'primary'; const initialValues: HabitFormValues | undefined = habit ? { colorToken: colorToken as HabitColorToken, description: habit.description ?? '', frequencyType: habit.frequency_type === 'daily' ? 'daily' : 'weekly', icon: (habit.icon ?? 'heart-pulse') as HabitIconName, name: habit.name, reminderEnabled: Boolean(habit.reminder_time), reminderTime: habit.reminder_time?.slice(0, 5) ?? '', targetCount: String(habit.target_count), weekdays: habit.days_of_week } : undefined; return <Screen contentContainerStyle={styles.screen} scroll={false}><AppHeader action={<IconButton icon={ArrowLeft} label="Go back" onPress={() => router.back()} />} eyebrow="HABIT" subtitle="Adjust the schedule without losing history." title="Edit habit" />{details.habitQuery.isLoading || details.logsQuery.isLoading ? <LoadingState label="Loading habit…" /> : null}{details.habitQuery.error ? <ErrorState description="This habit could not be loaded." onRetry={() => void details.habitQuery.refetch()} title="Habit unavailable" /> : null}{initialValues ? <HabitForm initialValues={initialValues} onCancel={() => router.back()} onSubmit={async (values) => { const result = await mutation.mutateAsync(values); Alert.alert('Habit updated', result.reminderWarning ? `Habit saved, but the reminder could not be scheduled. ${result.reminderWarning}` : 'Your changes were saved.', [{ onPress: () => router.back(), text: 'Done' }]); }} submitLabel="Save changes" /> : null}</Screen>; }
const styles = StyleSheet.create({ screen: { flex: 1, gap: spacing.md } });
